if(NOT DEFINED GROUP2_ASSET_SOURCE)
    message(FATAL_ERROR "GROUP2_ASSET_SOURCE is required")
endif()

if(NOT DEFINED GROUP2_ASSET_DEST)
    message(FATAL_ERROR "GROUP2_ASSET_DEST is required")
endif()

file(REMOVE_RECURSE "${GROUP2_ASSET_DEST}")
file(MAKE_DIRECTORY "${GROUP2_ASSET_DEST}")
file(COPY "${GROUP2_ASSET_SOURCE}/"
     DESTINATION "${GROUP2_ASSET_DEST}"
     PATTERN "flipbooks" EXCLUDE
     PATTERN "*.g2vol" EXCLUDE)
