# cmake/EmbedShaders.cmake
#
# Invoked at BUILD TIME via `cmake -P` to convert compiled SPIR-V binaries
# into a C++ header with embedded constexpr byte arrays.
#
# Required -D arguments (set by add_custom_command in CMakeLists.txt):
#   SPV_LIST_FILE  — path to a text file containing one absolute .spv path per line
#   OUTPUT_FILE    — path to write the generated C++ header

cmake_minimum_required(VERSION 3.25)

if(NOT DEFINED SPV_LIST_FILE OR NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "EmbedShaders: SPV_LIST_FILE and OUTPUT_FILE must be defined via -D")
endif()

file(READ "${SPV_LIST_FILE}" _raw)
string(REPLACE "\n" ";" _all_files "${_raw}")
list(FILTER _all_files EXCLUDE REGEX "^[ \t]*$")  # drop blank lines

set(_body "")
foreach(SPV_FILE IN LISTS _all_files)
    get_filename_component(_name "${SPV_FILE}" NAME)       # scene.vert.spv
    string(REGEX REPLACE "[^a-zA-Z0-9]" "_" _var "${_name}")  # scene_vert_spv

    file(READ "${SPV_FILE}" _hex HEX)
    string(LENGTH "${_hex}" _hex_len)
    math(EXPR _byte_count "${_hex_len} / 2")

    # "aabb..." → "0xaa, 0xbb, ..."  (trailing comma is valid in C++11 initializers)
    string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1, " _bytes "${_hex}")

    string(APPEND _body
        "// ${_name} — ${_byte_count} bytes\n"
        "inline constexpr Uint8  k_spv_${_var}[]  = { ${_bytes}};\n"
        "inline constexpr Uint32 k_spv_${_var}_size = ${_byte_count}U;\n\n"
    )
    message(STATUS "EmbedShaders: embedded ${_name} (${_byte_count} bytes)")
endforeach()

file(WRITE "${OUTPUT_FILE}"
    "#pragma once\n"
    "// Auto-generated by cmake/EmbedShaders.cmake — do not edit, do not commit.\n"
    "// SPIR-V shaders are embedded as byte arrays for single-binary distribution.\n"
    "// Regenerated every build when TITANDOOM_BUNDLE_SHADERS is ON.\n"
    "#include <SDL3/SDL.h>\n\n"
    "${_body}"
)
